PREFIX bb5kbc: <http://w3id.org/bb5kbc/ont/>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?site ?label WHERE {
  ?site a bb5kbc:Fundstelle ;
        rdfs:label ?label
} ORDER BY ?label LIMIT 50
