PREFIX bb5kbc: <http://w3id.org/bb5kbc/ont/>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT (COUNT(DISTINCT ?site) AS ?sites) WHERE {
  ?site a/rdfs:subClassOf* crm:E27_Site
}
